services:
  aws-presentation:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aws-presentation
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/azureuser/certs:/etc/letsencrypt:ro
      - /home/azureuser/certs-data:/var/www/certbot:ro
